### ISSUE TITLE
Finalize the Queries to get Conferences Data

### ISSUE THREAD

**Issue by atapas** [bugfender/devresources.info#2]
For the Conferences page to work, we need the data from the Caisy CMS.

- [x] Define all the schema for conferences in Caisy
- [x] Define All the GrapgQL Queries for the conferences page and use cases
- [x] Create the relevant source code to capture the tested queries inside the project.

**Comment by prachi-sahu-codes** [comment]
Issue #2 Finalize the Queries to get Conferences Data completed
